completed css-brochure-form -Andrew Owyang
Ajowyang/c0724-code-solutions pull request #13
Opened 2024-07-17 17:56 UTC by Ajowyang

![Screenshot 2024-07-17 at 10 56 05 AM](https://github.com/user-attachments/assets/96f69528-d2a3-4642-83f9-00bb1dc64d10)

2024-07-17 18:01 UTC, brandon-moy requested changes
Great start! Have a few changes requested:

- Label boldness
- Label connecting to inputs
- Button text capitalization

2024-07-17 18:01 UTC, brandon-moy commented on css-brochure-form/index.html
> +        </div>
Your `labels` have a `for` attribute, but where is it connecting to?

2024-07-17 18:01 UTC, brandon-moy commented on css-brochure-form/index.html
> +          </div>
Same thing here with the `label` and `for` attribute

2024-07-17 18:01 UTC, brandon-moy commented on css-brochure-form/index.html
> +          </div>
Same thing here with the `label` and `for` attribute

2024-07-17 18:01 UTC, brandon-moy commented on css-brochure-form/index.html
> +        </div>
Same thing here with the `label` and `for` attribute.

Also if it is a `select`, should it only have one `option`? Even if you don't see it I would recommend adding 2 more options here. Also, what attribute should an `option` have so we know which was selected?

2024-07-17 22:13 UTC, Ajowyang commented
<img width="400" alt="Screenshot 2024-07-17 at 3 13 32 PM" src="https://github.com/user-attachments/assets/0b33aa01-024e-437f-8aca-e253c0528cca">

2024-07-17 23:40 UTC, brandon-moy requested changes
Still need to address:

- Labels connecting to correct inputs/form elements
- Additional select options and how we get the value of the select

2024-07-18 15:44 UTC, brandon-moy approved these changes
👍

2024-07-25 16:53 UTC, merged