completed css-layout-classes
Ajowyang/c0724-code-solutions pull request #15
Opened 2024-07-17 23:58 UTC by Ajowyang

![Screenshot 2024-07-17 at 4 57 57 PM](https://github.com/user-attachments/assets/4c639fbf-417a-4997-8510-9340cf09299e)
![Screenshot 2024-07-17 at 4 58 02 PM](https://github.com/user-attachments/assets/fc04b3c4-eb89-4f00-9aeb-7cb5dccd94a3)

2024-07-17 23:59 UTC, Ajowyang commented
Are my Kirby fox pikachu and ness larger than they should be?

2024-07-18 00:05 UTC, brandon-moy requested changes
Great start but a couple of things here as well as in comments:

Your four images in a row are larger than intended to be. This is because while you have your container items for them set to a specific width, you are not specifying the width of the image element to max that.

Also when you name classes in HTML/CSS, you should use `kebab-case` rather than `camelCase`. `camelCase` is used more in your TypeScript for variables and functions.

2024-07-18 00:05 UTC, brandon-moy commented on css-layout-classes/styles.css
> +}
While technically yes, 200px is 1/4 of your 800px, what happens if you change your `container`'s `max-width`? Then you have to come back down and adjust any rules that are also modified by it. Instead you should be using a percentage.

2024-07-18 00:05 UTC, brandon-moy commented on css-layout-classes/index.html
> +          </p>
Should these be `column-half`? In the reference image are they `half` or more/less than `half` for each piece?

Also I don't see a CSS ruleset for `columnHalf` so where was this getting styled from?

2024-07-18 17:51 UTC, brandon-moy approved these changes
👍

2024-07-25 18:04 UTC, merged